### ISSUE TITLE
Je zet hier de breedte alleen voor de elementen met class="input", waarom niet voor alle?

### ISSUE THREAD

**Issue by JeroenHeemskerk** [Stijn121/educom-webshop-basis-1691483875#18]
https://github.com/Stijn121/educom-webshop-basis-1691483875/blob/01130295d1147162115c5e20139452287e14a13a/CSS/stylesheet.css#L20-L26

Ik zou alle Inputs op 400 px zetten en misschien diegene van type radio en type submit weer terugzetten op 'auto'
```CSS
input { 
     font-size: 12px; 
     color: darkgray; 
     width: 400px; 
 } 
 input[type="radio"], input[type="submit"] { 
     width: auto; 
 } 
```
